/// Flutter icons Bottle
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Bottle
///      fonts:
///       - asset: fonts/Bottle.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Bottle {
  Bottle._();

  static const _kFontFam = 'Bottle';
  static const String? _kFontPkg = null;

  static const IconData feeding_bottle = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
